version: '3.8'

services:
  # Vue.js frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sanity
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Sanity CMS backend
  sanity:
    build:
      context: ./vnews-feed
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    restart: unless-stopped